Added credits. Inspired by user Roliga, added functionality to wait to hibernate domain. Also, added functionality to stop other service nosleep.

diff --git a/bin/libvirt-dohibernate b/bin/libvirt-dohibernate
--- a/bin/libvirt-dohibernate
+++ b/bin/libvirt-dohibernate
@@ -2,8 +2,9 @@
 
 #
 # Filename:       /usr/local/bin/libvirt-dohibernate
-# Description:    Try to hibernate Libvirt domain before Host hibernation.
-# Author(s):      Alex Portell <github.com/portellam>
+# Description:    Hibernate Libvirt domain.
+# URL(s):         https://web.archive.org/web/20220808031554/https://old.reddit.com/r/VFIO/comments/8ypedp/for_anyone_getting_issues_with_their_guest_when/
+# Author(s):      Roliga <reddit.com/u/Roliga>
 # Maintainer(s):  Alex Portell <github.com/portellam>
 #
 
@@ -12,28 +13,15 @@
   HOOK_NAME="dohibernate"
   PREFIX_ERROR="An error occurred:"
   PREFIX_PROMPT="libvirt-qemu ${HOOK_NAME}:"
+  HOOK_NOSLEEP_SERVICE="libvirt-nosleep@${DOMAIN_NAME}"
 # </params>
 
 # <functions>
   function main
   {
     is_domain_suspended_or_offline && return 0
-
-    if ! hibernate_domain \
-      || ! sleep_for_one_cycle \
-      || ! is_domain_suspended_or_offline; then
-      return 1
-    fi
-  }
-
-  function print_prompt_to_log
-  {
-    echo -e "${PREFIX_PROMPT} ${1}" >&1
-  }
-
-  function print_error_to_log
-  {
-    echo -e "${PREFIX_PROMPT} ${PREFIX_ERROR} ${1}" >&2
+    hibernate_domain || return 1
+    stop_nosleep_service
   }
 
   function hibernate_domain
@@ -43,25 +31,50 @@
       return 1
     fi
 
-    print_prompt_to_log "Hibernating Libvirt domain '${DOMAIN_NAME}'."
+    while ! is_domain_suspended_or_offline; do
+      sleep_for_one_cycle
+    done
   }
 
   function is_domain_suspended_or_offline
   {
-    local -r domain_state="$( virsh domstate ${DOMAIN_NAME} | tr -d '\n' )"
+    local -r domain_state="$( virsh domstate "${DOMAIN_NAME}" | tr -d '\n' )"
 
-    if [[ "${domain_state}" != *"pmsuspended"* ]] \
-      && [[ "${domain_state}" != *"shut off"* ]]; then
-      print_error_to_log "Libvirt domain '${DOMAIN_NAME}' is online."
-      return 1
-    fi
+    case "${domain_state}" in
+      *"pmsuspended"* )
+        print_prompt_to_log "Libvirt domain '${DOMAIN_NAME}' is suspended."
+        return 0 ;;
 
-    print_prompt_to_log "Libvirt domain '${DOMAIN_NAME}' is offline."
+      *"shut off"* )
+        print_prompt_to_log "Libvirt domain '${DOMAIN_NAME}' is offline."
+        return 0 ;;
+    esac
+
+    return 1
+  }
+
+  function print_prompt_to_log
+  {
+    echo -e "${PREFIX_PROMPT} ${1}" >&2
+  }
+
+  function print_error_to_log
+  {
+    echo -e "${PREFIX_PROMPT} ${PREFIX_ERROR} ${1}" >&2
   }
 
   function sleep_for_one_cycle
   {
+    print_prompt_to_log "Waiting for Libvirt domain '${DOMAIN_NAME}' to hibernate."
     sleep 1
+  }
+
+  function stop_nosleep_service
+  {
+    if ! systemctl stop "${HOOK_NOSLEEP_SERVICE}" &> /dev/null; then
+      print_error_to_log "Failed to stop '${HOOK_NOSLEEP_SERVICE}' service."
+      return 1
+    fi
   }
 # </functions>
 
