Reorganized code. Reformatted comments. Adhered to 80/24 rule.

diff --git a/hooks/set-hooks.d/start-and-stop/cfscpu b/hooks/set-hooks.d/start-and-stop/cfscpu
--- a/hooks/set-hooks.d/start-and-stop/cfscpu
+++ b/hooks/set-hooks.d/start-and-stop/cfscpu
@@ -2,14 +2,15 @@
 
 #
 # Filename:       /etc/libvirt/hooks/cfscpu
-# Description:    Set the "nice level" of the Completely Fair Scheduler of vCPU threads.
+# Description:    Set the "nice level" of the Completely Fair Scheduler of vCPU
+#                 threads.
 # URL(s):         https://github.com/PassthroughPOST/VFIO-Tools
 # Author(s):      Danny Lin <danny@kdrag0n.dev>
 # Maintainer(s):  Alex Portell <codeberg.org/portellam> <github.com/portellam>
 # Version:        1.0.0
 #
 
-# <remarks>
+#
 # This hook sets the CFS "nice level" of the vCPU threads to the configured
 # value. This can be useful as a replacement for using the real-time FIFO
 # scheduling policy (SCHED_FIFO) through libvirt since it causes lockups on
@@ -22,145 +23,245 @@
 # set the user's default nice level instead. Some setups necessitate running
 # QEMU as another user for PulseAudio or other reasons, which is where this
 # script is useful.
-# </remarks>
+#
 
-# <params>
+#
+# params
+#
   DOMAIN_NAME="${1}"
 
-  # <summary>Append output</summary>
+  #
+  # DESC: append output
+  #
     PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
     PREFIX_ERROR="${PREFIX_PROMPT}An error occurred: "
     PREFIX_FAIL="${PREFIX_PROMPT}Failure: "
     PREFIX_PASS="${PREFIX_PROMPT}Success: "
     PREFIX_SKIP="${PREFIX_PROMPT}Skipped: "
 
-  # <remarks>Ranges from 20 (lowest priority) to -20 (highest priority).</remarks>
-  TARGET_NICE="-1"
-# </params>
+  #
+  # DESC: Ranges from 20 (lowest priority) to -20 (highest priority).
+  #
+    TARGET_NICE="-1"
 
-# <functions>
-  function main
-  {
-    local -r output="cfscpu"
-    print_output_to_log "${output}"
+#
+# logic
+#
+  #
+  # DESC:   Main execution.
+  # RETURN: If execution is successful, return 0.
+  #         If not, return 1.
+  #
+    function main
+    {
+      local -r str_output="cfscpu"
+      log_output "${str_output}"
 
-    if is_valid_domain; then
-      print_skip_to_log "${output}"
+      if is_valid_domain; then
+        log_skip "${str_output}"
+        return 0
+      fi
+
+      if ! get_vcpu_path \
+        || ! prioritize_vcpu_for_domain; then
+        log_fail "${str_output}"
+        return 1
+      fi
+
+      log_pass "${str_output}"
       return 0
-    fi
-
-    if ! get_vcpu_path \
-      || ! prioritize_vcpu_for_domain; then
-      print_fail_to_log "${output}"
-      return 1
-    fi
-
-    print_pass_to_log "${output}"
-  }
-
-  # <summary>Loggers</summary>
-    function print_error
-    {
-      echo -e "${PREFIX_ERROR}${1}"
     }
 
-    function print_error_to_log
+  #
+  # DESC: loggers
+  #
+    #
+    # DESC:   Log the output as an error.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_error
+      {
+        echo -e "${PREFIX_ERROR}${1}" >&2
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a fail.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_fail
+      {
+        echo -e "${PREFIX_FAIL}${1}" >&2
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a fail.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_output
+      {
+        echo -e "${PREFIX_PROMPT}${1}" >&1
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a pass.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_pass
+      {
+        echo -e "${PREFIX_PASS}${1}" >&1
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a skip.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_skip
+      {
+        echo -e "${PREFIX_SKIP}${1}" >&1
+        return 0
+      }
+
+  #
+  # DESC:   Get the vCPU path.
+  # RETURN: If successful, return 0.
+  #         If not, return 1.
+  #
+    function get_vcpu_path
     {
-      echo -e "${PREFIX_ERROR}${1}" >&2
+      if is_vcpu_path_in_subdirectory; then
+        VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/"\
+          "machine-qemu*${DOMAIN_NAME}.scope/libvirt/vcpu*"
+      else
+        VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/"\
+          "machine-qemu*${DOMAIN_NAME}.scope/vcpu*"
+      fi
+
+      return 0
     }
 
-    function print_fail_to_log
+  #
+  # DESC:   Is the vCPU path in the Libvirt subdirectory.
+  # RETURN: If true, return 0.
+  #         If not, return 1.
+  #
+    function is_vcpu_path_in_subdirectory
     {
-      echo -e "${PREFIX_FAIL}${1}" >&2
+      if ! ls "/sys/fs/cgroup/cpu/machine.slice/machine-qemu*${DOMAIN_NAME}.scope/"\
+        "libvirt/vcpu*" 1> /dev/null 2>&2; then
+
+        print_prompt "Failed to find vCPU paths in Libvirt subdirectory. Found vCPU "\
+          "directory." > /dev/kmsg
+
+        return 1
+      fi
+
+      print_prompt "Found vCPU paths in Libvirt subdirectory." > /dev/kmsg
+      return 0
     }
 
-    function print_output
+  #
+  # DESC:   Is the domain valid.
+  # RETURN: If successful, return 0.
+  #         If not, return 1.
+  #
+    function is_valid_domain
     {
-      echo -e "${PREFIX_PROMPT}${1}"
+      if [[ ! -z "${DOMAIN_NAME}" ]]; then
+        log_error "Invalid Libvirt domain."
+        return 1
+      fi
+
+      return 0
     }
 
-    function print_output_to_log
+  #
+  # DESC:   Prioritize vCPU threads for domain.
+  # RETURN: If successful, return 0.
+  #         If not, return 1.
+  #
+    function prioritize_vcpu_for_domain
     {
-      echo -e "${PREFIX_PROMPT}${1}" >&1
+      if ! set_nice_level_for_domain; then
+
+        log_error "Failed to prioritize vCPU threads of Libvirt domain "\
+          "'${DOMAIN_NAME}'" > /dev/kmsg
+
+        return 1
+      fi
+
+      log_output "Prioritized vCPU threads of Libvirt domain '${DOMAIN_NAME}'" \
+        > /dev/kmsg
+
+      return 0
     }
 
-    function print_pass_to_log
+  #
+  # DESC:   Set the nice level for every vCPU group.
+  # RETURN: If the nice level is set successfully, return 0.
+  #         If not, return 1.
+  #
+    function set_nice_level_for_domain
     {
-      echo -e "${PREFIX_PASS}${1}" >&1
+      for vcpu_group in ${VCPU_PATH}; do
+        if ! set_nice_level_for_vcpu_group "${vcpu_group}"; then
+          return 1
+        fi
+      done
+
+      return 0
     }
 
-    function print_skip_to_log
+  #
+  # DESC:   Set the nice level for the process ID.
+  # $1:     the process ID as a string.
+  # RETURN: If the nice level is set successfully, return 0.
+  #         If not, return 1.
+  #
+    function set_nice_level_for_process_id
     {
-      echo -e "${PREFIX_SKIP}${1}" >&1
+      local -r pid="${1}"
+
+      if ! renice -n "${TARGET_NICE}" -p "${pid}" 2> /dev/null; then
+        log_error "Failed to set nice level for PID '${pid}'."
+        return 1
+      fi
+
+      log_output "Set nice level for PID '${pid}'."
+      return 0
     }
 
-  function get_vcpu_path
-  {
-    if is_vcpu_path_in_subdirectory; then
-      VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/machine-qemu*${DOMAIN_NAME}.scope/libvirt/vcpu*"
-    else
-      VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/machine-qemu*${DOMAIN_NAME}.scope/vcpu*"
-    fi
-  }
+  #
+  # DESC:   Set the nice level for the vCPU group.
+  # $1:     the vCPU group as a string.
+  # RETURN: If the nice level is set successfully, return 0.
+  #         If not, return 1.
+  #
+    function set_nice_level_for_vcpu_group
+    {
+      local -r vcpu_group="${1}"
 
-  function is_vcpu_path_in_subdirectory
-  {
-    if ! ls /sys/fs/cgroup/cpu/machine.slice/machine-qemu*${DOMAIN_NAME}.scope/libvirt/vcpu* 1> /dev/null 2>&2; then
-      print_prompt "Failed to find vCPU paths in Libvirt subdirectory. Found vCPU directory." > /dev/kmsg
-      return 1
-    fi
+      print_output "Setting nice level of ${TARGET_NICE} to vCPU group "\
+        "'$( basename ${vcpu_group} ).'" > /dev/kmsg
 
-    print_prompt "Found vCPU paths in Libvirt subdirectory." > /dev/kmsg
-  }
+      for pid in $( cat ${vcpu_group}/tasks ); do
+        if ! set_nice_level_for_process_id "${pid}"; then
+          return 1
+        fi
+      done
 
-  function is_valid_domain
-  {
-    if [[ ! -z "${DOMAIN_NAME}" ]]; then
-      print_error_to_log "Invalid Libvirt domain."
-      return 1
-    fi
-  }
+      return 0
+    }
 
-  function prioritize_vcpu_for_domain
-  {
-    if ! set_nice_level_for_domain; then
-      print_error_to_log "Failed to prioritize vCPU threads of Libvirt domain '${DOMAIN_NAME}'" > /dev/kmsg
-      return 1
-    fi
-
-    print_output_to_log "Prioritized vCPU threads of Libvirt domain '${DOMAIN_NAME}'" > /dev/kmsg
-  }
-
-  function set_nice_level_for_domain
-  {
-    for vcpu_group in ${VCPU_PATH}; do
-      set_nice_level_for_vcpu_group "${vcpu_group}" || return 1
-    done
-  }
-
-  function set_nice_level_for_process_id
-  {
-    local -r pid="${1}"
-
-    if ! renice -n "${TARGET_NICE}" -p "${pid}" 2> /dev/null; then
-      print_error_to_log "Failed to set nice level for PID '${pid}'."
-      return 1
-    fi
-
-    print_output_to_log "Set nice level for PID '${pid}'."
-  }
-
-  function set_nice_level_for_vcpu_group
-  {
-    local -r vcpu_group="${1}"
-    print_output "Setting nice level of ${TARGET_NICE} to vCPU group '$( basename ${vcpu_group} ).'" > /dev/kmsg
-
-    for pid in $( cat ${vcpu_group}/tasks ); do
-      set_nice_level_for_process_id "${pid}" || return 1
-    done
-  }
-# </functions>
-
-# <code>
+#
+# main
+#
   main
-# </code>
diff --git a/hooks/set-hooks.d/start-and-stop/hugepages b/hooks/set-hooks.d/start-and-stop/hugepages
--- a/hooks/set-hooks.d/start-and-stop/hugepages
+++ b/hooks/set-hooks.d/start-and-stop/hugepages
@@ -9,94 +9,142 @@
 # Version:        1.0.0
 #
 
-# <remarks>
+#
 # This hook only needs to run on `prepare/begin`, not on stop.
 #
-# This hook will help free and compact memory to ease Transparent HugePages
+# This hook will help free and compact memory to ease Transparent Hugepages
 # allocation (THP). QEMU VMs will use THP  by default if enough unfragmented memory
 # can be found on startup. If your memory is very fragmented, this may cause a slow VM
 # startup (like a slowly responding VM start button/command), and may cause QEMU to
 # fall back to regular memory pages, slowing down VM performance. If you suspect you
 # suffer from this, this hook will help ease THP allocation so you don't need to
 # resort to less understood or placebo scripts.
-# </remarks>
+#
 
-# <params>
-  # <summary>Append output</summary>
+#
+# params
+#
+  #
+  # DESC: append output
+  #
     PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
     PREFIX_ERROR="${PREFIX_PROMPT}An error occurred: "
     PREFIX_FAIL="${PREFIX_PROMPT}Failure: "
     PREFIX_PASS="${PREFIX_PROMPT}Success: "
-# </params>
 
-# <functions>
+#
+# logic
+#
   function main
   {
-    local -r output="Hugepages"
+    local -r str_output="Hugepages"
 
     if ! write_host_memory_to_storage \
       || ! drop_filesystem_caches \
       || ! write_host_memory_to_storage \
       || ! defragment_host_memory; then
-      print_fail_to_log "${output}"
+      log_fail "${str_output}"
       return 1
     fi
 
-    print_pass_to_log "${output}"
+    log_pass "${str_output}"
   }
 
-  # <summary>Loggers</summary>
-    function print_error_to_log
+  #
+  # DESC: loggers
+  #
+    #
+    # DESC:   Log the output as an error.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_error
+      {
+        echo -e "${PREFIX_ERROR}${1}" >&2
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a fail.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_fail
+      {
+        echo -e "${PREFIX_FAIL}${1}" >&2
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a fail.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_output
+      {
+        echo -e "${PREFIX_PROMPT}${1}" >&1
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a pass.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_pass
+      {
+        echo -e "${PREFIX_PASS}${1}" >&1
+        return 0
+      }
+
+  #
+  # DESC:   Defragment Host memory.
+  # RETURN: If successful, return 0.
+  #         If not, return 1.
+  #
+    function defragment_host_memory
     {
-      echo -e "${PREFIX_ERROR}${1}" >&2
+      if ! echo 1 > /proc/sys/vm/compact_memory; then
+        log_error "Failed to defragment Host memory."
+        return 1
+      fi
+
+      log_pass "Defragmented Host memory."
     }
 
-    function print_fail_to_log
+
+  #
+  # DESC:   Drop filesystem caches.
+  # RETURN: If successful, return 0.
+  #         If not, return 1.
+  #
+    function drop_filesystem_caches
     {
-      echo -e "${PREFIX_FAIL}${1}" >&2
+      if ! echo 3 > /proc/sys/vm/drop_caches; then
+        log_error "Failed to drop filesystem caches."
+        return 1
+      fi
+
+      log_pass "Dropped filesystem caches."
     }
 
-    function print_output_to_log
+  #
+  # DESC:   Write Host memory to storage.
+  # RETURN: If successful, return 0.
+  #         If not, return 1.
+  #
+    function write_host_memory_to_storage
     {
-      echo -e "${PREFIX_PROMPT}${1}" >&1
+      if ! sync; then
+        log_error "Failed to write Host memory to storage."
+        return 1
+      fi
+
+      log_pass "Wrote Host memory to storage."
+      return 0
     }
 
-    function print_pass_to_log
-    {
-      echo -e "${PREFIX_PASS}${1}" >&1
-    }
-
-  function write_host_memory_to_storage
-  {
-    if ! sync; then
-      print_error_to_log "Failed to write Host memory to storage."
-      return 1
-    fi
-
-    print_pass_to_log "Wrote Host memory to storage."
-  }
-
-  function drop_filesystem_caches
-  {
-    if ! echo 3 > /proc/sys/vm/drop_caches; then
-      print_error_to_log "Failed to drop filesystem caches."
-      return 1
-    fi
-
-    print_pass_to_log "Dropped filesystem caches."
-  }
-
-  function defragment_host_memory
-  {
-    if ! echo 1 > /proc/sys/vm/compact_memory; then
-      print_error_to_log "Failed to defragment Host memory."
-      return 1
-    fi
-
-    print_pass_to_log "Defragmented Host memory."
-  }
-# </functions>
-
-# <code>
+#
+# main
+#
   main
-# </code>
diff --git a/hooks/set-hooks.d/start-only/ddcutil b/hooks/set-hooks.d/start-only/ddcutil
--- a/hooks/set-hooks.d/start-only/ddcutil
+++ b/hooks/set-hooks.d/start-only/ddcutil
@@ -2,14 +2,15 @@
 
 #
 # Filename:       /etc/libvirt/hooks/ddcutil
-# Description:    Automatically switch monitor inputs when starting/stopping a libvirt domain.
+# Description:    Automatically switch monitor inputs when starting/stopping a libvirt
+#                 domain.
 # URL(s):         https://github.com/PassthroughPOST/VFIO-Tools
 # Author(s):      Sebastiaan <github.com/SharkWipf>
 # Maintainer(s):  Alex Portell <codeberg.org/portellam> <github.com/portellam>
 # Version:        1.0.0
 #
 
-# <remarks>
+#
 # This hook allows automatically switch monitor inputs when starting/stopping a VM.
 # This file depends on the Passthrough POST hook helper script found in this repo.
 # Place this script in BOTH these directories (or symlink it):
@@ -18,105 +19,168 @@
 # You also need `ddcutil` and a ddcutil-compatible monitor.
 #
 # Make sure you specify the right settings for your setup below or it won't work.
-# </remarks>
+#
 
-# return 0		# <note>Skipping: To be implemented in a future release</note>
-
-# <params>
+#
+# params
+#
 	OPERATION="${2}"
 	SUBOPERATION="${3}"
 
-  # <summary>Append output</summary>
+  #
+  # DESC: append output
+  #
     PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
     PREFIX_ERROR="${PREFIX_PROMPT}An error occurred: "
     PREFIX_FAIL="${PREFIX_PROMPT}Failure: "
     PREFIX_PASS="${PREFIX_PROMPT}Success: "
 
-	# <remarks>The display shown in `ddcutil detect`</remarks>
-	DOMAIN_DISPLAY="0"
+	# The display shown in `ddcutil detect'.
+    DOMAIN_DISPLAY="0"
 
-	# <remarks>Video input values (without 0x, but with leading zeroes, if any. See `ddcutil capabilities`)</remarks>
-	DOMAIN_VIDEO_INPUT="12"
-	HOST_VIDEO_INPUT="0f"
-	VIDEO_INPUT=""
-# </params>
+	# Video input values (without 0x, but with leading zeroes, if any.
+  # See `ddcutil capabilities`.
+    DOMAIN_VIDEO_INPUT="12"
+    HOST_VIDEO_INPUT="0f"
+    VIDEO_INPUT=""
 
-# <functions>
-	function main
-	{
-		local -r output="ddcutil"
-		print_output_to_log "${output}"
-
-		if ! get_video_input \
-			|| ! set_video_input; then
-			print_fail_to_log "${output}"
-			return 1
-		fi
-
-		print_pass_to_log "${output}"
-	}
-
-	# <summary>Loggers</summary>
-    function print_error_to_log
+#
+# logic
+#
+  #
+  # DESC:   main execution
+  # RETURN: If succesful, return 0.
+  #         If not, return 1.
+  #
+    function main
     {
-      echo -e "${PREFIX_ERROR}${1}" >&2
+      local -r str_output="ddcutil"
+      log_output "${str_output}"
+
+      if ! get_video_input \
+        || ! set_video_input; then
+        log_fail "${str_output}"
+        return 1
+      fi
+
+      log_pass "${str_output}"
+      return 0
     }
 
-    function print_fail_to_log
+  #
+  # DESC: loggers
+  #
+    #
+    # DESC:   Log the output as an error.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_error
+      {
+        echo -e "${PREFIX_ERROR}${1}" >&2
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a fail.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_fail
+      {
+        echo -e "${PREFIX_FAIL}${1}" >&2
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a fail.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_output
+      {
+        echo -e "${PREFIX_PROMPT}${1}" >&1
+        return 0
+      }
+
+    #
+    # DESC:   Log the output as a pass.
+    # $1:     the output as a string.
+    # RETURN: Always return 0.
+    #
+      function log_pass
+      {
+        echo -e "${PREFIX_PASS}${1}" >&1
+        return 0
+      }
+
+  #
+  # DESC:   Log the output as a pass.
+  # $1:     the output as a string.
+  # RETURN: Always return 0.
+  #
+    function get_video_input
     {
-      echo -e "${PREFIX_FAIL}${1}" >&2
+      case "${OPERATION}/${SUBOPERATION}" in
+        "started/begin" )
+          VIDEO_INPUT="${DOMAIN_VIDEO_INPUT}"
+          return 0 ;;
+
+        "stopped/end" )
+          VIDEO_INPUT="${HOST_VIDEO_INPUT}"
+          return 0 ;;
+      esac
+
+      return 1
     }
 
-    function print_output_to_log
+  #
+  # DESC:   Log the output as a pass.
+  # RETURN: Always return 0.
+  #
+    function has_switched_video_input
     {
-      echo -e "${PREFIX_PROMPT}${1}" >&1
+      if [[ \
+          "$( ddcutil -d "${DOMAIN_DISPLAY}" getvcp 60 --terse | awk '{print $4}' )" \
+            == "x${VIDEO_INPUT}" \
+        ]]; then
+        log_output "Video input is already set."
+      fi
+
+      return 0
     }
 
-    function print_pass_to_log
+  #
+  # DESC:   Log the output as a pass.
+  # RETURN: Always return 0.
+  #
+    function set_video_input
     {
-      echo -e "${PREFIX_PASS}${1}" >&1
+      if has_switched_video_input; then
+        return 0
+      fi
+
+      switch_video_input
+      return 0
     }
 
-	function get_video_input
-	{
-		case "${OPERATION}/${SUBOPERATION}" in
-			"started/begin" )
-				VIDEO_INPUT="${DOMAIN_VIDEO_INPUT}"
-				return 0 ;;
+  #
+  # DESC:   Log the output as a pass.
+  # $1:     the output as a string.
+  # RETURN: Always return 0.
+  #
+    function switch_video_input
+    {
+      if ! ddcutil -d "${DOMAIN_DISPLAY}" setvcp 60 "0x${VIDEO_INPUT}"; then
+        log_error "Failed to switch video input."
+        return 1
+      fi
 
-			"stopped/end" )
-				VIDEO_INPUT="${HOST_VIDEO_INPUT}"
-				return 0 ;;
-		esac
+      log_output "Switched video input."
+      return 0
+    }
 
-		return 1
-	}
-
-	function switch_video_input
-	{
-		if ! ddcutil -d "${DOMAIN_DISPLAY}" setvcp 60 "0x${VIDEO_INPUT}"; then
-			print_error_to_log "Failed to switch video input."
-			return 1
-		fi
-
-		print_output_to_log "Switched video input."
-	}
-
-	function has_switched_video_input
-	{
-		if [[ "$( ddcutil -d "${DOMAIN_DISPLAY}" getvcp 60 --terse | awk '{print $4}' )" == "x${VIDEO_INPUT}" ]]; then
-			print_output_to_log "Video input is already set."
-			return 0
-		fi
-	}
-
-	function set_video_input
-	{
-		has_switched_video_input && return 0
-		switch_video_input
-	}
-# </functions>
-
-# <code>
+#
+# main
+#
 	main
-# </code>
