Modified params.

diff --git a/hooks/set-hooks.d/start-and-stop/hugepages b/hooks/set-hooks.d/start-and-stop/hugepages
--- a/hooks/set-hooks.d/start-and-stop/hugepages
+++ b/hooks/set-hooks.d/start-and-stop/hugepages
@@ -21,19 +21,66 @@
 # allocation so you don't need to resort to misexplained placebo scripts.
 # </remarks>
 
-  PREFIX_ERROR="An error occurred:"
-  PREFIX_PROMPT="libvirt-qemu $( basename "${0}" ):"
+
+# <params>
+  # <summary>
+  # Color coding
+  # Reference URL: 'https://www.shellhacks.com/bash-colors'
+  # </summary>
+    SET_COLOR_GREEN='\033[0;32m'
+    SET_COLOR_RED='\033[0;31m'
+    SET_COLOR_YELLOW='\033[0;33m'
+    RESET_COLOR='\033[0m'
+
+  # <summary>Append output</summary>
+    PREFIX_PROMPT="libvirt-qemu $( basename "${0}" ):"
+    PREFIX_ERROR="${PREFIX_PROMPT}${SET_COLOR_YELLOW}An error occurred:${RESET_COLOR} "
+    PREFIX_FAIL="${PREFIX_PROMPT}${SET_COLOR_RED}Failure:${RESET_COLOR} "
+    PREFIX_PASS="${PREFIX_PROMPT}${SET_COLOR_GREEN}Success:${RESET_COLOR} "
+    PREFIX_SKIP="${PREFIX_PROMPT}${SET_COLOR_YELLOW}Skipped:${RESET_COLOR} "
+# </params>
 
 # <functions>
   function main
   {
+    local -r output="Hugepages"
+
     if ! write_host_memory_to_storage \
       || ! drop_filesystem_caches \
       || ! write_host_memory_to_storage \
       || ! defragment_host_memory; then
+      print_fail_to_log "${output}"
       return 1
     fi
+
+    print_pass_to_log "${output}"
   }
+
+  # <summary>Loggers</summary>
+    function print_error_to_log
+    {
+      echo -e "${PREFIX_ERROR}${1}" >&2
+    }
+
+    function print_fail_to_log
+    {
+      echo -e "${PREFIX_FAIL}${1}" >&2
+    }
+
+    function print_output_to_log
+    {
+      echo -e "${PREFIX_PROMPT}${1}" >&1
+    }
+
+    function print_pass_to_log
+    {
+      echo -e "${PREFIX_PASS}${1}" >&1
+    }
+
+    function print_skip_to_log
+    {
+      echo -e "${PREFIX_SKIP}${1}" >&1
+    }
 
   function write_host_memory_to_storage
   {
@@ -42,7 +89,7 @@
       return 1
     fi
 
-    print_output_to_log "Wrote Host memory to storage."
+    print_pass_to_log "Wrote Host memory to storage."
   }
 
   function drop_filesystem_caches
@@ -52,7 +99,7 @@
       return 1
     fi
 
-    print_output_to_log "Dropped filesystem caches."
+    print_pass_to_log "Dropped filesystem caches."
   }
 
   function defragment_host_memory
@@ -62,17 +109,7 @@
       return 1
     fi
 
-    print_output_to_log "Defragmented Host memory."
-  }
-
-  function print_output_to_log
-  {
-    echo -e "${PREFIX_PROMPT} ${1}" >&2
-  }
-
-  function print_error_to_log
-  {
-    echo -e "${PREFIX_PROMPT} ${PREFIX_ERROR} ${1}" >&2
+    print_pass_to_log "Defragmented Host memory."
   }
 # </functions>
 
