Removed print_prompt.

diff --git a/hooks/set-hooks.d/start-and-stop/hugepages b/hooks/set-hooks.d/start-and-stop/hugepages
--- a/hooks/set-hooks.d/start-and-stop/hugepages
+++ b/hooks/set-hooks.d/start-and-stop/hugepages
@@ -65,19 +65,14 @@
     print_prompt_to_log "Defragmented Host memory."
   }
 
-  function print_prompt
-  {
-    echo -e "${PREFIX_PROMPT} ${1}"
-  }
-
   function print_prompt_to_log
   {
-    print_prompt "${1}" >&1
+    echo -e "${PRINT_PROMPT} ${1}" >&1
   }
 
   function print_error_to_log
   {
-    print_prompt "${PREFIX_ERROR} ${1}" >&2
+    echo -e "${PRINT_PROMPT} ${PREFIX_ERROR} ${1}" >&2
   }
 # </functions>
 
diff --git a/hooks/set-service b/hooks/set-service
--- a/hooks/set-service
+++ b/hooks/set-service
@@ -42,19 +42,14 @@
     set_operation "${service_name}" "${operation}" || return 1
   }
 
-  function print_prompt
-  {
-    echo -e "${PREFIX_PROMPT} ${1}"
-  }
-
   function print_prompt_to_log
   {
-    print_prompt "${1}" >&1
+    echo -e "${PRINT_PROMPT} ${1}" >&1
   }
 
   function print_error_to_log
   {
-    print_prompt "${PREFIX_ERROR} ${1}" >&2
+    echo -e "${PRINT_PROMPT} ${PREFIX_ERROR} ${1}" >&2
   }
 
   function set_operation
