Reverted nosleep for now.

diff --git a/hooks/nosleep b/hooks/nosleep
--- a/hooks/nosleep
+++ b/hooks/nosleep
@@ -2,23 +2,43 @@
 
 #
 # Filename:       /etc/libvirt/hooks/nosleep
-# Description:    Prevent Host suspend while Libvirt domain is online.
-# Author(s):      Alex Portell <github.com/portellam>
+# Description:    Prevent host sleep while libvirt domain is running.
+# URL(s):         https://web.archive.org/web/20220808031554/https://old.reddit.com/r/VFIO/comments/8ypedp/for_anyone_getting_issues_with_their_guest_when/
+# Author(s):      sm-Fifteen <reddit.com/u/sm-Fifteen>
 # Maintainer(s):  Alex Portell <github.com/portellam>
 #
 
-# <sources>
-  source set-service
-# </sources>
+HOOK_NAME="nosleep"
+PREFIX_ERROR="An error occurred:"
+PREFIX_PROMPT="libvirt-qemu ${HOOK_NAME}:"
+DOMAIN_NAME="${1}"
+OPERATION="${2}"
 
-# <params>
-  DOMAIN_NAME="${1}"
-  HOOK_NAME="$( basename "${0}" )"
-  THIS_SERVICE_NAME="libvirt-${HOOK_NAME}@${DOMAIN_NAME}.service"
-  REAL_SERVICE_NAME="libvirt-${HOOK_NAME}@.service"
-  SERVICE_FULL_PATH="/etc/systemd/system/libvirt-${REAL_SERVICE_NAME}@.service"
-# </params>
+function start_service
+{
+  if ! systemctl start "libvirt-nosleep@${DOMAIN_NAME}" &> /dev/null; then
+    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to start 'libvirt-nosleep@${DOMAIN_NAME}' service." >&2
+    return 1
+  fi
 
-# <code>
-  setup_this_service "${THIS_SERVICE_NAME}" "${SERVICE_FULL_PATH}" "$@"
-# </code>
+  echo "${PREFIX_PROMPT} Started 'libvirt-nosleep@${DOMAIN_NAME}' service."
+  return 0
+}
+
+function stop_service
+{
+  if ! systemctl stop "libvirt-nosleep@${DOMAIN_NAME}" &> /dev/null; then
+    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to stop 'libvirt-nosleep@${DOMAIN_NAME}' service." >&2
+    return 1
+  fi
+
+  echo "${PREFIX_PROMPT} Stopped 'libvirt-nosleep@${DOMAIN_NAME}' service."
+  return 0
+}
+
+case "${OPERATION}" in
+  "prepare")
+    start_service ;;
+  "release")
+    stop_service ;;
+esac
