Added hungarian notation to main parameters.

diff --git a/hooks/set-service b/hooks/set-service
--- a/hooks/set-service
+++ b/hooks/set-service
@@ -14,11 +14,11 @@
   #
   # DESC: append output
   #
-    PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
-    PREFIX_ERROR="${PREFIX_PROMPT}An error occurred: "
-    PREFIX_FAIL="${PREFIX_PROMPT}Failure: "
-    PREFIX_PASS="${PREFIX_PROMPT}Success: "
-    PREFIX_SKIP="${PREFIX_PROMPT}Skipped: "
+    STR_PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
+    STR_PREFIX_ERROR="${STR_PREFIX_PROMPT}An error occurred: "
+    STR_PREFIX_FAIL="${STR_PREFIX_PROMPT}Failure: "
+    STR_PREFIX_PASS="${STR_PREFIX_PROMPT}Success: "
+    STR_PREFIX_SKIP="${STR_PREFIX_PROMPT}Skipped: "
 
 #
 # logic
@@ -69,7 +69,7 @@
     #
       function log_error
       {
-        echo -e "${PREFIX_ERROR}${1}" >&2
+        echo -e "${STR_PREFIX_ERROR}${1}" >&2
         return 0
       }
 
@@ -80,7 +80,7 @@
     #
       function log_fail
       {
-        echo -e "${PREFIX_FAIL}${1}" >&2
+        echo -e "${STR_PREFIX_FAIL}${1}" >&2
         return 0
       }
 
@@ -91,7 +91,7 @@
     #
       function log_output
       {
-        echo -e "${PREFIX_PROMPT}${1}" >&1
+        echo -e "${STR_PREFIX_PROMPT}${1}" >&1
         return 0
       }
 
@@ -102,7 +102,7 @@
     #
       function log_pass
       {
-        echo -e "${PREFIX_PASS}${1}" >&1
+        echo -e "${STR_PREFIX_PASS}${1}" >&1
         return 0
       }
 
@@ -113,7 +113,7 @@
     #
       function log_skip
       {
-        echo -e "${PREFIX_SKIP}${1}" >&1
+        echo -e "${STR_PREFIX_SKIP}${1}" >&1
         return 0
       }
 
@@ -154,6 +154,42 @@
         fi
 
         log_output "Enabled '${str_service_name}' service."
+        return 0
+      }
+
+    #
+    # DESC:   Is the operation argument valid.
+    # $1:     the operation argument as a string.
+    # RETURN: If valid, return 0.
+    #         If not valid, return 1.
+    #
+      function is_argument_valid
+      {
+        local -r str_operation="${1}"
+
+        if [[ -z "${str_operation}" ]]; then
+          log_error "Operation argument is not valid."
+          return 1
+        fi
+
+        return 0
+      }
+
+    #
+    # DESC:   Is the service name valid.
+    # $1:     the service name as a string.
+    # RETURN: If valid, return 0.
+    #         If not valid, return 1.
+    #
+      function is_service_name_valid
+      {
+        local -r str_service_name="${1}"
+
+        if [[ -z "${str_service_name}" ]]; then
+          log_error "Service name is not valid."
+          return 1
+        fi
+
         return 0
       }
 
@@ -223,42 +259,6 @@
             fi
             ;;
         esac
-
-        return 0
-      }
-
-    #
-    # DESC:   Is the service name valid.
-    # $1:     the service name as a string.
-    # RETURN: If valid, return 0.
-    #         If not valid, return 1.
-    #
-      function is_service_name_valid
-      {
-        local -r str_service_name="${1}"
-
-        if [[ -z "${str_service_name}" ]]; then
-          log_error "Service name is not valid."
-          return 1
-        fi
-
-        return 0
-      }
-
-    #
-    # DESC:   Is the operation argument valid.
-    # $1:     the operation argument as a string.
-    # RETURN: If valid, return 0.
-    #         If not valid, return 1.
-    #
-      function is_argument_valid
-      {
-        local -r str_operation="${1}"
-
-        if [[ -z "${str_operation}" ]]; then
-          log_error "Operation argument is not valid."
-          return 1
-        fi
 
         return 0
       }
