Added hungarian notation to main params. Added return statements.

diff --git a/hooks/set-hooks b/hooks/set-hooks
--- a/hooks/set-hooks
+++ b/hooks/set-hooks
@@ -21,41 +21,41 @@
 #
 # params
 #
-  DOMAIN_NAME="${1}"
+  STR_DOMAIN_NAME="${1}"
 
   #
   # DESC: append output
   #
-    PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
-    PREFIX_ERROR="${PREFIX_PROMPT}An error occurred: "
-    PREFIX_FAIL="${PREFIX_PROMPT}Failure: "
-    PREFIX_PASS="${PREFIX_PROMPT}Success: "
-    PREFIX_SKIP="${PREFIX_PROMPT}Skipped: "
+    STR_PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
+    STR_PREFIX_ERROR="${STR_PREFIX_PROMPT}An error occurred: "
+    STR_PREFIX_FAIL="${STR_PREFIX_PROMPT}Failure: "
+    STR_PREFIX_PASS="${STR_PREFIX_PROMPT}Success: "
+    STR_PREFIX_SKIP="${STR_PREFIX_PROMPT}Skipped: "
 
-  HOOKS_BASE_DIR="$( dirname $( realpath "${0}" ) )/"
-  DOMAIN_NAME_BASE_DIR="${HOOKS_BASE_DIR}qemu.d/${DOMAIN_NAME}/"
-  DOMAIN_NAME_START_DIR="${DOMAIN_NAME_BASE_DIR}started/begin/"
-  DOMAIN_NAME_STOP_DIR="${DOMAIN_NAME_BASE_DIR}stopped/end/"
+  STR_HOOKS_BASE_DIR="$( dirname $( realpath "${0}" ) )/"
+  STR_DOMAIN_NAME_BASE_DIR="${STR_HOOKS_BASE_DIR}qemu.d/${STR_DOMAIN_NAME}/"
+  STR_DOMAIN_NAME_START_DIR="${STR_DOMAIN_NAME_BASE_DIR}started/begin/"
+  STR_DOMAIN_NAME_STOP_DIR="${STR_DOMAIN_NAME_BASE_DIR}stopped/end/"
 
-  STATEFUL_HOOKS_DIR="${0}.d/"
-  STATEFUL_HOOKS_START_ONLY_DIR="${STATEFUL_HOOKS_DIR}start-only/"
-  STATEFUL_HOOKS_STOP_ONLY_DIR="${STATEFUL_HOOKS_DIR}stop-only/"
-  STATEFUL_HOOKS_BOTH_DIR="${STATEFUL_HOOKS_DIR}start-and-stop/"
+  STR_STATEFUL_HOOKS_DIR="${0}.d/"
+  STR_STATEFUL_HOOKS_START_ONLY_DIR="${STR_STATEFUL_HOOKS_DIR}start-only/"
+  STR_STATEFUL_HOOKS_STOP_ONLY_DIR="${STR_STATEFUL_HOOKS_DIR}stop-only/"
+  STR_STATEFUL_HOOKS_BOTH_DIR="${STR_STATEFUL_HOOKS_DIR}start-and-stop/"
 
-  STATEFUL_HOOKS_START_LIST=( \
-    $( find -L "${STATEFUL_HOOKS_START_ONLY_DIR}" -maxdepth 1 -type f ) \
+  ARR_STATEFUL_HOOKS_START_LIST=( \
+    $( find -L "${STR_STATEFUL_HOOKS_START_ONLY_DIR}" -maxdepth 1 -type f ) \
   )
 
-  STATEFUL_HOOKS_START_LIST+=( \
-    $( find -L "${STATEFUL_HOOKS_BOTH_DIR}" -maxdepth 1 -type f ) \
+  ARR_STATEFUL_HOOKS_START_LIST+=( \
+    $( find -L "${STR_STATEFUL_HOOKS_BOTH_DIR}" -maxdepth 1 -type f ) \
   )
 
-  STATEFUL_HOOKS_STOP_LIST=( \
-    $( find -L "${STATEFUL_HOOKS_STOP_ONLY_DIR}" -maxdepth 1 -type f ) \
+  ARR_STATEFUL_HOOKS_STOP_LIST=( \
+    $( find -L "${STR_STATEFUL_HOOKS_STOP_ONLY_DIR}" -maxdepth 1 -type f ) \
   )
 
-  STATEFUL_HOOKS_STOP_LIST+=( \
-    $( find -L "${STATEFUL_HOOKS_BOTH_DIR}" -maxdepth 1 -type f ) \
+  ARR_STATEFUL_HOOKS_STOP_LIST+=( \
+    $( find -L "${STR_STATEFUL_HOOKS_BOTH_DIR}" -maxdepth 1 -type f ) \
   )
 
 #
@@ -97,7 +97,7 @@
     #
       function log_error
       {
-        echo -e "${PREFIX_ERROR}${1}" >&2
+        echo -e "${STR_PREFIX_ERROR}${1}" >&2
         return 0
       }
 
@@ -108,7 +108,7 @@
     #
       function log_fail
       {
-        echo -e "${PREFIX_FAIL}${1}" >&2
+        echo -e "${STR_PREFIX_FAIL}${1}" >&2
         return 0
       }
 
@@ -119,7 +119,7 @@
     #
       function log_output
       {
-        echo -e "${PREFIX_PROMPT}${1}" >&1
+        echo -e "${STR_PREFIX_PROMPT}${1}" >&1
         return 0
       }
 
@@ -130,7 +130,7 @@
     #
       function log_pass
       {
-        echo -e "${PREFIX_PASS}${1}" >&1
+        echo -e "${STR_PREFIX_PASS}${1}" >&1
         return 0
       }
 
@@ -141,7 +141,7 @@
     #
       function log_skip
       {
-        echo -e "${PREFIX_SKIP}${1}" >&1
+        echo -e "${STR_PREFIX_SKIP}${1}" >&1
         return 0
       }
 
@@ -155,10 +155,10 @@
     #
       function get_paths_for_domain
       {
-        if ! create_directory "${DOMAIN_NAME_BASE_DIR}" \
-          || ! create_directory "${DOMAIN_NAME_START_DIR}" \
-          || ! create_directory "${DOMAIN_NAME_STOP_DIR}"; then
-          log_error "Failed to create directories for Libvirt domain '${DOMAIN}'."
+        if ! create_directory "${STR_DOMAIN_NAME_BASE_DIR}" \
+          || ! create_directory "${STR_DOMAIN_NAME_START_DIR}" \
+          || ! create_directory "${STR_DOMAIN_NAME_STOP_DIR}"; then
+          log_error "Failed to create directories for Libvirt domain '${STR_DOMAIN}'."
           return 1
         fi
 
@@ -174,7 +174,7 @@
       {
         for str_hook_name in "${HOOKS_LIST[@]}"; do
           if [[ ! -e "${HOOK_BASE_DIR}${str_hook_name}" ]]; then
-            log_error "Failed to find hook(s) for Libvirt domain '${DOMAIN}'."
+            log_error "Failed to find hook(s) for Libvirt domain '${STR_DOMAIN}'."
             return 1
           fi
         done
@@ -215,17 +215,17 @@
         local -r str_domain="${str_domain}"
 
         if [[ -z "${str_domain}" ]] \
-          || [[ ! -e "${DOMAIN_NAME_START_DIR}${str_domain}" ]]; then
+          || [[ ! -e "${STR_DOMAIN_NAME_START_DIR}${str_domain}" ]]; then
           return 0
         fi
 
-        if ! ln -s "${DOMAIN_NAME_START_DIR}${str_domain}" \
+        if ! ln -s "${STR_DOMAIN_NAME_START_DIR}${str_domain}" \
           "${HOOK_BASE_DIR}${str_domain}" &> /dev/null; then
           log_error "Failed to set symlinks for start hook '${str_domain}'."
           return 1
         fi
 
-        if ! chmod +x "${DOMAIN_NAME_START_DIR}${str_domain}" &> /dev/null; then
+        if ! chmod +x "${STR_DOMAIN_NAME_START_DIR}${str_domain}" &> /dev/null; then
           log_error "Failed to set file permissions for start hook '${str_domain}'."
           return 1
         fi
@@ -244,17 +244,17 @@
         local -r str_domain="${1}"
 
         if [[ -z "${1}" ]] \
-          || [[ ! -e "${DOMAIN_NAME_STOP_DIR}${str_domain}" ]]; then
+          || [[ ! -e "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" ]]; then
           return 0
         fi
 
-        if ! ln -s "${DOMAIN_NAME_STOP_DIR}${str_domain}" \
+        if ! ln -s "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" \
           "${HOOK_BASE_DIR}${str_domain}" &> /dev/null; then
           log_error "Failed to set symlinks for stop hook '${str_domain}'."
           return 1
         fi
 
-        if ! chmod +x "${DOMAIN_NAME_STOP_DIR}${str_domain}" &> /dev/null; then
+        if ! chmod +x "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" &> /dev/null; then
           log_error "Failed to set file permissions for stop hook '${str_domain}'."
           return 1
         fi
@@ -268,13 +268,13 @@
     #
       function setup_stateful_hooks
       {
-        for str_hook in "${STATEFUL_HOOKS_START_LIST[@]}"; do
+        for str_hook in "${ARR_STATEFUL_HOOKS_START_LIST[@]}"; do
           if ! set_start_hook_for_domain "${str_hook}"; then
             unset_hook_for_domain "${str_hook}"
           fi
         done
 
-        for str_hook in "${STATEFUL_HOOKS_STOP_LIST[@]}"; do
+        for str_hook in "${ARR_STATEFUL_HOOKS_STOP_LIST[@]}"; do
           if ! set_stop_hook_for_domain "${str_hook}"; then
             unset_hook_for_domain "${str_hook}"
           fi
@@ -297,14 +297,14 @@
           return 0
         fi
 
-        if [[ ! -e "${DOMAIN_NAME_START_DIR}${str_domain}" ]] \
-          && ! rm -rf "${DOMAIN_NAME_START_DIR}${str_domain}" &> /dev/null; then
+        if [[ ! -e "${STR_DOMAIN_NAME_START_DIR}${str_domain}" ]] \
+          && ! rm -rf "${STR_DOMAIN_NAME_START_DIR}${str_domain}" &> /dev/null; then
           log_error "Failed to unset symlinks for start hook '${str_domain}'."
           return 1
         fi
 
-        if [[ ! -z "${DOMAIN_NAME_STOP_DIR}${str_domain}" ]] \
-          && ! rm -rf "${DOMAIN_NAME_STOP_DIR}${str_domain}" &> /dev/null; then
+        if [[ ! -z "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" ]] \
+          && ! rm -rf "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" &> /dev/null; then
           log_error "Failed to unset symlinks for stop hook '${str_domain}'."
           return 1
         fi
@@ -319,8 +319,8 @@
   #
     function is_valid_domain
     {
-      if [[ ! -z "${DOMAIN_NAME}" ]]; then
-        log_error "Stateful hook requires a Libvirt domain '${DOMAIN}'."
+      if [[ ! -z "${STR_DOMAIN_NAME}" ]]; then
+        log_error "Stateful hook requires a Libvirt domain '${STR_DOMAIN}'."
         return 1
       fi
 
diff --git a/hooks/set-hooks.d/start-and-stop/cfscpu b/hooks/set-hooks.d/start-and-stop/cfscpu
--- a/hooks/set-hooks.d/start-and-stop/cfscpu
+++ b/hooks/set-hooks.d/start-and-stop/cfscpu
@@ -28,21 +28,22 @@
 #
 # params
 #
-  DOMAIN_NAME="${1}"
+  STR_DOMAIN_NAME="${1}"
+  STR_VCPU_PATH=""
 
   #
   # DESC: append output
   #
-    PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
-    PREFIX_ERROR="${PREFIX_PROMPT}An error occurred: "
-    PREFIX_FAIL="${PREFIX_PROMPT}Failure: "
-    PREFIX_PASS="${PREFIX_PROMPT}Success: "
-    PREFIX_SKIP="${PREFIX_PROMPT}Skipped: "
+    STR_PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
+    STR_PREFIX_ERROR="${STR_PREFIX_PROMPT}An error occurred: "
+    STR_PREFIX_FAIL="${STR_PREFIX_PROMPT}Failure: "
+    STR_PREFIX_PASS="${STR_PREFIX_PROMPT}Success: "
+    STR_PREFIX_SKIP="${STR_PREFIX_PROMPT}Skipped: "
 
   #
   # DESC: Ranges from 20 (lowest priority) to -20 (highest priority).
   #
-    TARGET_NICE="-1"
+    STR_TARGET_NICE_LEVEL="-1"
 
 #
 # logic
@@ -82,7 +83,7 @@
     #
       function log_error
       {
-        echo -e "${PREFIX_ERROR}${1}" >&2
+        echo -e "${STR_PREFIX_ERROR}${1}" >&2
         return 0
       }
 
@@ -93,7 +94,7 @@
     #
       function log_fail
       {
-        echo -e "${PREFIX_FAIL}${1}" >&2
+        echo -e "${STR_PREFIX_FAIL}${1}" >&2
         return 0
       }
 
@@ -104,7 +105,7 @@
     #
       function log_output
       {
-        echo -e "${PREFIX_PROMPT}${1}" >&1
+        echo -e "${STR_PREFIX_PROMPT}${1}" >&1
         return 0
       }
 
@@ -115,7 +116,7 @@
     #
       function log_pass
       {
-        echo -e "${PREFIX_PASS}${1}" >&1
+        echo -e "${STR_PREFIX_PASS}${1}" >&1
         return 0
       }
 
@@ -126,7 +127,7 @@
     #
       function log_skip
       {
-        echo -e "${PREFIX_SKIP}${1}" >&1
+        echo -e "${STR_PREFIX_SKIP}${1}" >&1
         return 0
       }
 
@@ -138,11 +139,11 @@
     function get_vcpu_path
     {
       if is_vcpu_path_in_subdirectory; then
-        VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/"\
-          "machine-qemu*${DOMAIN_NAME}.scope/libvirt/vcpu*"
+        STR_VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/"\
+          "machine-qemu*${STR_DOMAIN_NAME}.scope/libvirt/vcpu*"
       else
-        VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/"\
-          "machine-qemu*${DOMAIN_NAME}.scope/vcpu*"
+        STR_VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/"\
+          "machine-qemu*${STR_DOMAIN_NAME}.scope/vcpu*"
       fi
 
       return 0
@@ -155,8 +156,8 @@
   #
     function is_vcpu_path_in_subdirectory
     {
-      if ! ls "/sys/fs/cgroup/cpu/machine.slice/machine-qemu*${DOMAIN_NAME}.scope/"\
-        "libvirt/vcpu*" 1> /dev/null 2>&2; then
+      if ! ls "/sys/fs/cgroup/cpu/machine.slice/machine-qemu*${STR_DOMAIN_NAME}"\
+        ".scope/libvirt/vcpu*" 1> /dev/null 2>&2; then
 
         print_prompt "Failed to find vCPU paths in Libvirt subdirectory. Found vCPU "\
           "directory." > /dev/kmsg
@@ -175,7 +176,7 @@
   #
     function is_valid_domain
     {
-      if [[ ! -z "${DOMAIN_NAME}" ]]; then
+      if [[ ! -z "${STR_DOMAIN_NAME}" ]]; then
         log_error "Invalid Libvirt domain."
         return 1
       fi
@@ -193,12 +194,12 @@
       if ! set_nice_level_for_domain; then
 
         log_error "Failed to prioritize vCPU threads of Libvirt domain "\
-          "'${DOMAIN_NAME}'" > /dev/kmsg
+          "'${STR_DOMAIN_NAME}'" > /dev/kmsg
 
         return 1
       fi
 
-      log_output "Prioritized vCPU threads of Libvirt domain '${DOMAIN_NAME}'" \
+      log_output "Prioritized vCPU threads of Libvirt domain '${STR_DOMAIN_NAME}'" \
         > /dev/kmsg
 
       return 0
@@ -211,7 +212,7 @@
   #
     function set_nice_level_for_domain
     {
-      for str_vcpu_group in ${VCPU_PATH}; do
+      for str_vcpu_group in ${STR_VCPU_PATH}; do
         if ! set_nice_level_for_vcpu_group "${str_vcpu_group}"; then
           return 1
         fi
@@ -230,7 +231,7 @@
     {
       local -r str_pid="${1}"
 
-      if ! renice -n "${TARGET_NICE}" -p "${str_pid}" 2> /dev/null; then
+      if ! renice -n "${STR_TARGET_NICE_LEVEL}" -p "${str_pid}" 2> /dev/null; then
         log_error "Failed to set nice level for PID '${str_pid}'."
         return 1
       fi
@@ -249,11 +250,11 @@
     {
       local -r str_cpu_group="${1}"
 
-      print_output "Setting nice level of ${TARGET_NICE} to vCPU group "\
+      print_output "Setting nice level of ${STR_TARGET_NICE_LEVEL} to vCPU group "\
         "'$( basename ${str_cpu_group} ).'" > /dev/kmsg
 
-      for pid in $( cat ${str_cpu_group}/tasks ); do
-        if ! set_nice_level_for_process_id "${pid}"; then
+      for str_pid in $( cat ${str_cpu_group}/tasks ); do
+        if ! set_nice_level_for_process_id "${str_pid}"; then
           return 1
         fi
       done
diff --git a/hooks/set-hooks.d/start-and-stop/hugepages b/hooks/set-hooks.d/start-and-stop/hugepages
--- a/hooks/set-hooks.d/start-and-stop/hugepages
+++ b/hooks/set-hooks.d/start-and-stop/hugepages
@@ -27,10 +27,10 @@
   #
   # DESC: append output
   #
-    PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
-    PREFIX_ERROR="${PREFIX_PROMPT}An error occurred: "
-    PREFIX_FAIL="${PREFIX_PROMPT}Failure: "
-    PREFIX_PASS="${PREFIX_PROMPT}Success: "
+    STR_PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
+    STR_PREFIX_ERROR="${STR_PREFIX_PROMPT}An error occurred: "
+    STR_PREFIX_FAIL="${STR_PREFIX_PROMPT}Failure: "
+    STR_PREFIX_PASS="${STR_PREFIX_PROMPT}Success: "
 
 #
 # logic
@@ -48,6 +48,7 @@
     fi
 
     log_pass "${str_output}"
+    return 0
   }
 
   #
@@ -60,7 +61,7 @@
     #
       function log_error
       {
-        echo -e "${PREFIX_ERROR}${1}" >&2
+        echo -e "${STR_PREFIX_ERROR}${1}" >&2
         return 0
       }
 
@@ -71,7 +72,7 @@
     #
       function log_fail
       {
-        echo -e "${PREFIX_FAIL}${1}" >&2
+        echo -e "${STR_PREFIX_FAIL}${1}" >&2
         return 0
       }
 
@@ -82,7 +83,7 @@
     #
       function log_output
       {
-        echo -e "${PREFIX_PROMPT}${1}" >&1
+        echo -e "${STR_PREFIX_PROMPT}${1}" >&1
         return 0
       }
 
@@ -93,7 +94,7 @@
     #
       function log_pass
       {
-        echo -e "${PREFIX_PASS}${1}" >&1
+        echo -e "${STR_PREFIX_PASS}${1}" >&1
         return 0
       }
 
@@ -110,6 +111,7 @@
       fi
 
       log_pass "Defragmented Host memory."
+      return 0
     }
 
 
@@ -126,6 +128,7 @@
       fi
 
       log_pass "Dropped filesystem caches."
+      return 0
     }
 
   #
