Added logger functions and function calls. Reorganized functions.

diff --git a/hooks/set-hooks b/hooks/set-hooks
--- a/hooks/set-hooks
+++ b/hooks/set-hooks
@@ -42,15 +42,132 @@
 # <functions>
   function main
   {
-    is_valid_domain || return 0
+    saveifs="${IFS}"
+    IFS=$'\n'
+    local -r output="Set hooks"
+    print_output_to_log "${output}"
 
-    if ! get_paths_for_domain \
+    if ! is_valid_domain \
+      || ! get_paths_for_domain \
       || ! get_hooks; then
+      print_fail_to_log "${output}"
       return 1
     fi
 
     setup_stateful_hooks
   }
+
+  # <summary>Loggers</summary>
+    function print_error_to_log
+    {
+      echo -e "${PREFIX_ERROR}${1}" >&2
+    }
+
+    function print_fail_to_log
+    {
+      echo -e "${PREFIX_FAIL}${1}" >&2
+    }
+
+    function print_output_to_log
+    {
+      echo -e "${PREFIX_PROMPT}${1}" >&1
+    }
+
+    function print_pass_to_log
+    {
+      echo -e "${PREFIX_PASS}${1}" >&1
+    }
+
+    function print_skip_to_log
+    {
+      echo -e "${PREFIX_SKIP}${1}" >&1
+    }
+
+  # <summary>Getters</summary>
+    function get_paths_for_domain
+    {
+      if ! create_directory "${DOMAIN_NAME_BASE_DIR}" \
+        || ! create_directory "${DOMAIN_NAME_START_DIR}" \
+        || ! create_directory "${DOMAIN_NAME_STOP_DIR}"; then
+        print_error_to_log "Failed to create directories for Libvirt domain '${DOMAIN}'."
+        return 1
+      fi
+    }
+
+    function get_hooks
+    {
+      for hook_name in "${HOOKS_LIST[@]}"; do
+        if [[ ! -e "${HOOK_BASE_DIR}${hook_name}" ]]; then
+          print_error_to_log "Failed to find hook(s) for Libvirt domain '${DOMAIN}'."
+          return 1
+        fi
+      done
+    }
+
+  # <summary>Validation</summary>
+    function is_valid_domain
+    {
+      if [[ ! -z "${DOMAIN_NAME}" ]]; then
+        print_error_to_log "Stateful hook requires a Libvirt domain '${DOMAIN}'."
+        return 1
+      fi
+    }
+
+  # <summary>Setters</summary>
+    function set_start_hook_for_domain
+    {
+      if [[ -z "${1}" ]] \
+        || [[ ! -e "${DOMAIN_NAME_START_DIR}${1}" ]]; then
+        return 0
+      fi
+
+      if ! ln -s "${DOMAIN_NAME_START_DIR}${1}" "${HOOK_BASE_DIR}${1}" &> /dev/null; then
+        print_error_to_log "Failed to set symlinks for start hook '${1}'."
+        return 1
+      fi
+
+      if ! chmod +x "${DOMAIN_NAME_START_DIR}${1}" &> /dev/null; then
+        print_error_to_log "Failed to set file permissions for start hook '${1}'."
+        return 1
+      fi
+    }
+
+    function set_stop_hook_for_domain
+    {
+      if [[ -z "${1}" ]] \
+        || [[ ! -e "${DOMAIN_NAME_STOP_DIR}${1}" ]]; then
+        return 0
+      fi
+
+      if ! ln -s "${DOMAIN_NAME_STOP_DIR}${1}" "${HOOK_BASE_DIR}${1}" &> /dev/null; then
+        print_error_to_log "Failed to set symlinks for stop hook '${1}'."
+        return 1
+      fi
+
+      if ! chmod +x "${DOMAIN_NAME_STOP_DIR}${1}" &> /dev/null; then
+        print_error_to_log "Failed to set file permissions for stop hook '${1}'."
+        return 1
+      fi
+    }
+
+    function unset_hook_for_domain
+    {
+      if [[ -z "${1}" ]]; then
+        return 0
+      fi
+
+      if [[ ! -e "${DOMAIN_NAME_START_DIR}${1}" ]] \
+        && ! rm -rf "${DOMAIN_NAME_START_DIR}${1}" &> /dev/null; then
+        print_error_to_log "Failed to unset symlinks for start hook '${1}'."
+        return 1
+      fi
+
+      if [[ ! -z "${DOMAIN_NAME_STOP_DIR}${1}" ]] \
+        && ! rm -rf "${DOMAIN_NAME_STOP_DIR}${1}" &> /dev/null; then
+        print_error_to_log "Failed to unset symlinks for stop hook '${1}'."
+        return 1
+      fi
+    }
 
   function create_directory
   {
@@ -58,86 +175,8 @@
 
     if [[ -d "${dir}" ]] \
       && ! mkdir --parents "${dir}" &> /dev/null; then
-      print_error_to_log "Failed to create directory "${dir}"."
+      print_error_to_log "Failed to create directory '${dir}'."
     fi
-  }
-
-  function get_paths_for_domain
-  {
-    if ! create_directory "${DOMAIN_NAME_BASE_DIR}" \
-      || ! create_directory "${DOMAIN_NAME_START_DIR}" \
-      || ! create_directory "${DOMAIN_NAME_STOP_DIR}"; then
-      print_error_to_log "Failed to create directories for domain."
-      return 1
-    fi
-  }
-
-  function get_hooks
-  {
-    for hook_name in "${HOOKS_LIST[@]}"; do
-      if [[ ! -e "${HOOK_BASE_DIR}${hook_name}" ]]; then
-        print_error_to_log "Failed to find domain hook(s)."
-        return 1
-      fi
-    done
-  }
-
-  function is_valid_domain
-  {
-    if [[ ! -z "${DOMAIN_NAME}" ]]; then
-      return 1
-    fi
-  }
-
-  function print_prompt_to_log
-  {
-    echo -e "${PREFIX_PROMPT} ${1}" >&2
-  }
-
-  function print_error_to_log
-  {
-    echo -e "${PREFIX_PROMPT} ${PREFIX_ERROR} ${1}" >&2
-  }
-
-  function set_start_hook_for_domain
-  {
-    if [[ -z "${1}" ]] \
-      || [[ ! -e "${DOMAIN_NAME_START_DIR}${1}" ]]; then
-      return 0
-    fi
-
-    if ! ln -s "${DOMAIN_NAME_START_DIR}${1}" "${HOOK_BASE_DIR}${1}" &> /dev/null; then
-      print_error_to_log "Failed to set symlinks for start hook '${1}'."
-      return 1
-    fi
-
-    if ! chmod +x "${DOMAIN_NAME_START_DIR}${1}" &> /dev/null; then
-      print_error_to_log "Failed to set file permissions for start hook '${1}'."
-      return 1
-    fi
-  }
-
-  function set_stop_hook_for_domain
-  {
-    if [[ -z "${1}" ]] \
-      || [[ ! -e "${DOMAIN_NAME_STOP_DIR}${1}" ]]; then
-      return 0
-    fi
-
-    if ! ln -s "${DOMAIN_NAME_STOP_DIR}${1}" "${HOOK_BASE_DIR}${1}" &> /dev/null; then
-      print_error_to_log "Failed to set symlinks for stop hook '${1}'."
-      return 1
-    fi
-
-    if ! chmod +x "${DOMAIN_NAME_STOP_DIR}${1}" &> /dev/null; then
-      print_error_to_log "Failed to set file permissions for stop hook '${1}'."
-      return 1
-    fi
-  }
-
-  function set_ifs_to_newline
-  {
-    IFS=$'\n'
   }
 
   function setup_stateful_hooks
@@ -149,30 +188,6 @@
     for hook in "${STATEFUL_HOOKS_STOP_LIST[@]}"; do
       set_stop_hook_for_domain "${hook}" || unset_hook_for_domain "${hook}"
     done
-  }
-
-  function unset_hook_for_domain
-  {
-    if [[ -z "${1}" ]]; then
-      return 0
-    fi
-
-    if [[ ! -e "${DOMAIN_NAME_START_DIR}${1}" ]] \
-      && ! rm -rf "${DOMAIN_NAME_START_DIR}${1}" &> /dev/null; then
-      print_error_to_log "Failed to unset symlinks for start hook '${1}'."
-      return 1
-    fi
-
-    if [[ ! -z "${DOMAIN_NAME_STOP_DIR}${1}" ]] \
-      && ! rm -rf "${DOMAIN_NAME_STOP_DIR}${1}" &> /dev/null; then
-      print_error_to_log "Failed to unset symlinks for stop hook '${1}'."
-      return 1
-    fi
-  }
-
-  function unset_ifs
-  {
-    unset IFS
   }
 # </functions>
 
